name: Start Docker Container

on:
  push:
    branches:
      - main

jobs:
  start-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: |
          docker pull your-image-name  # Pull the Docker image from a registry
          docker run your-image-name   # Run the Docker container

      - name: Display name
        run: echo "Your First Name Last Name"
