name: Display Name on Push to Main

on:
  push:
    branches:
      - main

jobs:
  display-name:
    runs-on: ubuntu-latest  # Runner operating system
    steps:
      - uses: actions/checkout@v3 
      - name: Run Custom Script 
        run: |  # Multi-line command execution
          docker run --rm alpine echo "My name is Nat"  
         

