name: Show Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a bash script
      run: |
        echo "Running the docker image..."
        docker run -d --name my_container my_docker_image
        echo "Running the script inside the container..."
        docker exec -it my_container bash -c "echo 'First name: Nat'; echo 'Last name: S'"
